//
// Created by 85906 on 2/16/2024.
//

#ifndef H2OKEYBOARD_VERSION_H
#define H2OKEYBOARD_VERSION_H

#define FIRMWARE_VERSION_VERREG     (0)
#define FIRMWARE_VERSION_BASEREG    (0)
#define FIRMWARE_VERSION_DEVREG     (1)

#endif //H2OKEYBOARD_VERSION_H
